// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XustJKDKAutoRemind.Data;

namespace XustJKDKAutoRemind.Migrations
{
    [DbContext(typeof(QQStuContext))]
    [Migration("20211014173450_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("XustJKDKAutoRemind.Data.QQStu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GH")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("QQ")
                        .HasColumnType("TEXT");

                    b.Property<string>("XM")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QQStus");
                });
#pragma warning restore 612, 618
        }
    }
}
